name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  packages: write

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build_minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Get supported releases
        id: fedora
        uses: ./.github/actions/supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          release: ${{ steps.fedora.outputs.supported_releases }}
          target: minimal
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
  build_extra:
    runs-on: ubuntu-latest
    steps:
      - name: Get supported releases
        id: fedora
        uses: ./.github/actions/supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          release: ${{ steps.fedora.outputs.supported_releases }}
          target: extra
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
  build_all:
    runs-on: ubuntu-latest
    steps:
      - name: Get supported releases
        id: fedora
        uses: ./.github/actions/supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          release: ${{ steps.fedora.outputs.supported_releases }}
          target: all
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
